language: c

compiler:
  gcc
      
#before_install:
install:
  - sudo apt-get install check
  
script:
  #- make -C src 
  - make -C src -f Makefile_test
  - chmod +x bin/test-functions
  
after_script:
- ./bin/test-functions
