language: c

os:
  - osx

compiler:
  gcc

install:
  - brew install check 
  
script:
  - checkmk src/test-functions.check > src/test-functions.c
  - make -C src -f Makefile_test
  - chmod +x bin/test-functions

after_script:
- ./bin/test-functions
