/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test-functions.check" instead.
 */

#include <check.h>

#line 1 "test-functions.check"
#include "functions.h"
#include <stdlib.h>

START_TEST(theFunctions)
{
#line 5
int u, v, out;

u=1;
v=10;
out = 12;
 fail_unless(sum(&u, &v) == out, "output sum should be 11 not %d", out);
 

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, theFunctions);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf;
}
